version: "3.9"
services:
  server:
    image: "rawdagastan/c4s:backend"
    working_dir: /opt/project
    volumes:
      - .:/opt/project
    ports:
      - 3000:3000
    depends_on:
      - redis-db
 
  redis-db:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis-db

  frontend:
    environment:
      - VITE_API_ENDPOINT=http://localhost:3000/v1
    image: "mayarosama/cloud4students:latest"
    ports:
       - "8080:80"
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
